services:

  # Sevicio web con Apache y PHP para Laravel

  web:
    # Construye la imagen usando el Dockerfile creado
    build:
      context: ./docker/php
    container_name: laravel-apache-reto
    restart: unless-stopped
    # Mapea la carpeta local 'app' al directorio de trabajo del contenedor
    volumes:
      - ./src:/var/www/html
      
    # Expone el puerto 80 del contenedor al puerto 80 del host
    ports:
      # Tu puerto actual de la web
      - "80:80"
      # Añade esta línea para Vite
      #- "5173:5173"

    depends_on:
      - db
    # Conecta a la red interna
    networks:
      - laravel_network-reto


  # Gestion mySQL

  db:
    image: mysql:8.0
    container_name: laravel-mysql-reto
    restart: unless-stopped
    environment:
      # Variables de entorno de MySQL. ¡Cambia las contraseñas!
      MYSQL_ROOT_PASSWORD: root_password_segura
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password_segura
    # Mapea un volumen para persistir los datos de la base de datos
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network-reto


  # Gestion de la base de datos con phpMyAdmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin-reto
    restart: unless-stopped
    # Mapea el puerto 8080 del host al 80 del phpMyAdmin
    ports:
      - "8080:80"
    environment:
      # El host es el nombre del servicio Docker de la base de datos
      PMA_HOST: db
      # El puerto de MySQL dentro de la red Docker
      PMA_PORT: 3306 
    depends_on:
      - db
    networks:
      - laravel_network-reto


  node:
      image: node:22
      working_dir: /var/www/html
      volumes:
        - ./src:/var/www/html
      ports:
        - "5173:5173"
      #Se instalan dependencias y pone en marcha el servicio  
      command: sh -c "npm install && npm run dev -- --host"
      # Conecta a la red interna
      networks:
        - laravel_network-reto



# Redes y volumenes

networks:
  # Red interna para que los contenedores se comuniquen entre sí por nombre
  laravel_network-reto:
    driver: bridge

volumes:
  # Volumen para persistir los datos de MySQL
  dbdata:
